FROM node:lts-alpine
WORKDIR /app
RUN npm install -g @vue/cli

ENV NODE_ENV=development
COPY package-lock.json package.json node_modules* /app/
RUN npm install

COPY ./ /app

CMD ["npm", "run", "serve"]
