FROM node:lts-alpine as build
WORKDIR /app
RUN npm install -g @vue/cli

COPY ../../package-lock.json ../../package.json /app/
RUN npm install

COPY ../../ /app

ARG NODE_ENV=production
RUN npm run build

FROM node:lts-alpine
WORKDIR /app

RUN npm install -g serve

COPY --from=build /app/node_modules /app/dist /app/

EXPOSE 8080
CMD ["serve", "-p", "8080" "-s", "/app/dist"]
