version: '3.1'

services:
  backend:
    build: backend/
    restart: always
    ports:
      - 8085:8080
    environment:
      DB_URL: jdbc:mysql://db:3306/stuq_db
      DB_USERNAME: stuq_be
      DB_PASSWORD: db_user_pass
    labels:
      docker-compose-watcher.path: "backend/"

  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile-dev
    volumes:
      - ./frontend:/app
    restart: always
    ports:
      - 8080:8080