name: CI

on:
  pull_request:
    branches: [ master, dev, "setup/ci" ]
  workflow_dispatch:

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Build Docker image
      - uses: docker/build-push-action@v2
        with:
          tags: stuq-backend:latest
          push: false

    - name: Run Docker image, specifying to run tests
      - uses: addnab/docker-run-action@v3
        with:
          image: stuq-backend:latest
          run: mvn -Dserver.port=8085 spring-boot:test