name: CI

on:
  pull_request:
    branches: [ master, dev ]
  workflow_dispatch:

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./backend/
        tags: stuq-backend
        push: false
        load: true

    - name: Run Docker image, specifying to run tests
      uses: addnab/docker-run-action@v3
      with:
        image: stuq-backend
        run: mvn -Dserver.port=8085 spring-boot:test

  test-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./frontend/
        file: Dockerfile-dev
        tags: stuq-frontend
        push: false
        load: true

    - name: Run Docker image, specifying to run tests
      uses: addnab/docker-run-action@v3
      with:
        image: stuq-frontend
        run: npm run test:unit